### ISSUE TITLE
Why another cms based in silex?

### ISSUE THREAD

**Issue by hypervalley** [orthes/marvin#1]
I like Silex too. Nowadays there are two cms based on Silex : Bolt and PageKit . Why did you create yours? I have reservations about both and want to hear your opinion.
There are severals file based CMS being created. What do you think about change these CMS (or create a plugin) to accept databases, creating a hybrid cms?
If you interest, see these projects:
1. Spress (http://spress.yosymfony.com/): It is based in Symfony packages, Pimple and Twig, but is file based cms. 
2. Robodt (http://robodt.io/): "Out of the box CMS ditributions use the Slim framework, because it's lightweight, but it's easy to switch to other frameworks like Symfony, Silex, Fat-Free or Laravel."
The main idea is not invent the wheel and join interests.

**Comment by linkesch** [comment]
Hi! Sorry for my late answer. 

Both Bolt and PageKit matured a lot in the last year, so my reservations against both of them might be a little outdated. 

The idea behind Marvin is to provide a micro CMS for really simple websites that don't need advanced administration. An example would be a small website with 5 pages that would be changed only a few times a year. You don't need a professional CMS for that. You don't need advanced user roles, widgets and so on. 

Another important factor was to make it really, really easy to use for even unexperienced users. So I got rid of all those "SEO functions" like that a page could have different title, h1, and even menu label. Typically on most simple pages are all those the same.

Last but no least, I wanted to make it easily extendable, fully tested, build on a foundation of proven technologies (Silex, Bootstrap, PHPUnit, QUnit, Composer, Grunt, Bower...) and distributed via Composer. I wanted to make Marvin just another dependency. Not to force developers a separate folder structure.

So my reservations against Bolt and PageKit go along those lines. I was playing with both a year ago, so my informations might be really outdated:
- Bold - Administration looks too complicated for me.
- PageKit - Looks great now, but I don't remember it a year ago. I don't think you can install it via Composer.

I don't remember if they were tested a year ago, when I tried them.

Looking on those projects now, I don't think I would create a new CMS now. I think I would go with PageKit.

The biggest problem with Marvin now is that I didn't write a documentation for it. I'm using it on a few small websites without any problems, so I will write some docs so it can still be used. I don't know what will be the future it though.
