### ISSUE TITLE
Is there a easy way to apply MySQL

### ISSUE THREAD

**Issue by oovz** [orthes/marvin#2]
Hi orthes, thanks for this great cms.
However, I haven't used Silex before, and have no idea how to use MySQL in marvin.
Could u plz help me out :)

**Comment by linkesch** [comment]
Take a look here: https://github.com/orthes/marvin-pages/blob/master/Controller/AdminControllerProvider.php#L16

And official Silex docs here: http://silex.sensiolabs.org/doc/providers/doctrine.html

I hope it helps.

**Comment by oovz** [comment]
Thanks a lot !!
